In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [3]:
# preprocess the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [4]:
# label encoding 
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [5]:
# ohe 'Geography'
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

In [6]:
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [7]:
# combine the data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)

In [9]:
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [10]:
# train test split
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [11]:
with open('reg_label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('reg_onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
# Scale tese features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
with open('reg_scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [15]:
# ANN - regression
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [16]:
# Build ANN model
from tensorflow.keras.layers import Dropout

model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dropout(0.3),
    Dense(32, activation='relu'),
    Dropout(0.2),
    Dense(1)
])

c:\Users\jenis\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [17]:
# compile model
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])

model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
# train model
log_dir = 'regressionlogs/fit/' + datetime.datetime.now().strftime('%Y%m%d-%H%M%S')
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [19]:
# early stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [20]:
# Training model
history = model.fit(
    X_train, y_train, validation_data=(X_test, y_test), epochs=100,
    callbacks = [tensorboard_callback, early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 100389.1094 - mae: 100389.1094 - val_loss: 98553.4062 - val_mae: 98553.4062
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 99748.5156 - mae: 99748.5156 - val_loss: 97234.0078 - val_mae: 97234.0078
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 97435.2578 - mae: 97435.2578 - val_loss: 93794.2969 - val_mae: 93794.2969
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 92878.7578 - mae: 92878.7578 - val_loss: 88003.0000 - val_mae: 88003.0000
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 86087.8281 - mae: 86087.8281 - val_loss: 80353.2578 - val_mae: 80353.2578
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 77812.7656 - mae: 77812.7656 - val_loss: 71923.9062 - val_mae: 71923.9062
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 69564.8672 - mae: 69564.8672 - val_loss: 64195.2852 - val_mae: 64195.2852
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 62594.6602 - mae: 62594.6602 - val_loss: 58141.2773 - val_mae: 58141.2773
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 57534.9414 - mae: 57534.9414 - val_loss: 54202.2969 - val_mae: 54202.2969
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 54459.0078 - mae: 54459.0078 - val_loss: 52072.0430 - val_mae: 52072.0430
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 52828.9062 - mae: 52828.9062 - val_loss: 51061.9609 - val_mae: 51061.9609
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 52112.8203 - mae: 52112.8203 - val_loss: 50681.7070 - val_mae: 50681.7070
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51417.1445 - mae: 51417.1445 - val_loss: 50534.9492 - val_mae: 50534.9492
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51615.6094 - mae: 51615.6094 - val_loss: 50473.4688 - val_mae: 50473.4688
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51537.6055 - mae: 51537.6055 - val_loss: 50438.4492 - val_mae: 50438.4492
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51302.4297 - mae: 51302.4297 - val_loss: 50414.0195 - val_mae: 50414.0195
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51540.6523 - mae: 51540.6523 - val_loss: 50392.2383 - val_mae: 50392.2383
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51762.6914 - mae: 51762.6914 - val_loss: 50380.7383 - val_mae: 50380.7383
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51176.7617 - mae: 51176.7617 - val_loss: 50364.3008 - val_mae: 50364.3008
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51304.4023 - mae: 51304.4023 - val_loss: 50349.0469 - val_mae: 50349.0469
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51377.8516 - mae: 51377.8516 - val_loss: 50343.8398 - val_mae: 50343.8398
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51254.1484 - mae: 51254.1484 - val_loss: 50336.2148 - val_mae: 50336.2148
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51109.4609 - mae: 51109.4609 - val_loss: 50326.0625 - val_mae: 50326.0625
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50761.6523 - mae: 50761.6523 - val_loss: 50318.8242 - val_mae: 50318.8242
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51508.4297 - mae: 51508.4297 - val_loss: 50307.3125 - val_mae: 50307.3125
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 51056.4688 - mae: 51056.4688 - val_loss: 50298.5352 - val_mae: 50298.5352
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51003.2461 - mae: 51003.2461 - val_loss: 50297.0781 - val_mae: 50297.0781
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51167.7539 - mae: 51167.7539 - val_loss: 50290.1602 - val_mae: 50290.1602
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51283.9258 - mae: 51283.9258 - val_loss: 50282.2344 - val_mae: 50282.2344
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 51079.0352 - mae: 51079.0352 - val_loss: 50277.2695 - val_mae: 50277.2695
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50936.4258 - mae: 50936.4258 - val_loss: 50270.4609 - val_mae: 50270.4609
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50950.6055 - mae: 50950.6055 - val_loss: 50264.9258 - val_mae: 50264.9258
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50958.2188 - mae: 50958.2188 - val_loss: 50263.7109 - val_mae: 50263.7109
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50698.2969 - mae: 50698.2969 - val_loss: 50266.5625 - val_mae: 50266.5625
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50919.7227 - mae: 50919.7227 - val_loss: 50250.0742 - val_mae: 50250.0742
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51100.3477 - mae: 51100.3477 - val_loss: 50244.0508 - val_mae: 50244.0508
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51082.5977 - mae: 51082.5977 - val_loss: 50242.6406 - val_mae: 50242.6406
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51126.6914 - mae: 51126.6914 - val_loss: 50241.6016 - val_mae: 50241.6016
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51192.1367 - mae: 51192.1367 - val_loss: 50226.2422 - val_mae: 50226.2422
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50712.1992 - mae: 50712.1992 - val_loss: 50218.4023 - val_mae: 50218.4023
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51184.5742 - mae: 51184.5742 - val_loss: 50226.6562 - val_mae: 50226.6562
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50827.3555 - mae: 50827.3555 - val_loss: 50224.8945 - val_mae: 50224.8945
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51248.5742 - mae: 51248.5742 - val_loss: 50213.5898 - val_mae: 50213.5898
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50916.8047 - mae: 50916.8047 - val_loss: 50217.0352 - val_mae: 50217.0352
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51003.8867 - mae: 51003.8867 - val_loss: 50221.0000 - val_mae: 50221.0000
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51029.3438 - mae: 51029.3438 - val_loss: 50214.7344 - val_mae: 50214.7344
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50831.2969 - mae: 50831.2969 - val_loss: 50214.5352 - val_mae: 50214.5352
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51011.4102 - mae: 51011.4102 - val_loss: 50220.0547 - val_mae: 50220.0547
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 51031.6445 - mae: 51031.6445 - val_loss: 50212.3906 - val_mae: 50212.3906
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50904.2695 - mae: 50904.2695 - val_loss: 50222.1914 - val_mae: 50222.1914
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50948.4883 - mae: 50948.4883 - val_loss: 50220.9648 - val_mae: 50220.9648
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50896.0898 - mae: 50896.0898 - val_loss: 50217.9609 - val_mae: 50217.9609
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50895.7422 - mae: 50895.7422 - val_loss: 50200.8203 - val_mae: 50200.8203
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50993.4453 - mae: 50993.4453 - val_loss: 50210.6445 - val_mae: 50210.6445
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50921.7930 - mae: 50921.7930 - val_loss: 50203.2383 - val_mae: 50203.2383
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50833.6406 - mae: 50833.6406 - val_loss: 50208.1211 - val_mae: 50208.1211
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51129.1406 - mae: 51129.1406 - val_loss: 50202.8008 - val_mae: 50202.8008
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50837.1602 - mae: 50837.1602 - val_loss: 50200.5234 - val_mae: 50200.5234
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51245.8008 - mae: 51245.8008 - val_loss: 50197.2383 - val_mae: 50197.2383
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51042.6953 - mae: 51042.6953 - val_loss: 50199.6367 - val_mae: 50199.6367
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50912.5938 - mae: 50912.5938 - val_loss: 50201.8867 - val_mae: 50201.8867
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51114.0078 - mae: 51114.0078 - val_loss: 50205.1719 - val_mae: 50205.1719
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51040.1602 - mae: 51040.1602 - val_loss: 50203.2773 - val_mae: 50203.2773
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50704.9336 - mae: 50704.9336 - val_loss: 50203.9102 - val_mae: 50203.9102
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50746.1641 - mae: 50746.1641 - val_loss: 50194.5391 - val_mae: 50194.5391
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50927.5703 - mae: 50927.5703 - val_loss: 50196.4688 - val_mae: 50196.4688
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50960.6172 - mae: 50960.6172 - val_loss: 50192.6992 - val_mae: 50192.6992
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50930.7930 - mae: 50930.7930 - val_loss: 50208.5469 - val_mae: 50208.5469
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50703.7109 - mae: 50703.7109 - val_loss: 50213.0039 - val_mae: 50213.0039
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50728.1602 - mae: 50728.1602 - val_loss: 50215.3008 - val_mae: 50215.3008
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51002.6484 - mae: 51002.6484 - val_loss: 50211.0469 - val_mae: 50211.0469
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50984.6602 - mae: 50984.6602 - val_loss: 50209.7617 - val_mae: 50209.7617
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50728.0938 - mae: 50728.0938 - val_loss: 50211.1133 - val_mae: 50211.1133
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50885.3086 - mae: 50885.3086 - val_loss: 50210.5156 - val_mae: 50210.5156
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50805.9102 - mae: 50805.9102 - val_loss: 50215.2891 - val_mae: 50215.2891
Epoch 76/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51033.0430 - mae: 51033.0430 - val_loss: 50214.5117 - val_mae: 50214.5117
Epoch 77/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50860.2227 - mae: 50860.2227 - val_loss: 50205.8125 - val_mae: 50205.8125

In [21]:
%load_ext tensorboard

In [24]:
%tensorboard --logdir regressionlogs/fit/

Reusing TensorBoard on port 6006 (pid 25384), started 0:00:06 ago. (Use '!kill 25384' to kill it.)

In [25]:
# evaluate model
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f'Test MAE : {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50192.6992 - mae: 50192.6992
Test MAE : 50192.69921875

In [26]:
model.save('regression_model.keras')